### PR TITLE
Team 29 - Phase II Review

### PR DESCRIPTION
**Pull request by Bansenauer-Cascadia**

### CODE REVIEW

**Comment by Bansenauer-Cascadia** [comment]
**Complete and correct submissions:**

---
- All team members have committed content to the prototype branch
- App prototype uses good android coding practices as discussed in class
- Four (4) screens that clearly demonstrate behavior from at least two use cases
- One (1) data layout element (List or Grid) using a data adapter
- Two (2) Fragments that communicate via the Activity and respond to the Back button
- BONUS: Implementing music player
- BONUS: Implementing database login and change password
- BONUS: Implementing text animation

**Incorrect or missing items:**

---
- Localization in English and Chinese for all interface elements

---

**Notes:** Excellent work - a nice start to your app. Your prototype shows your design ideas well. I especially like the additional touches with the music and weather in "Write Diary"

**Comment by 12301154-jinsongkui** [comment]
Dear teacher,my name is jinsongkui-12301154,is your android class student,and i am the Team 29 leader,for Phase 2 ,you say that our team missong"Localization in English and Chinese for all interface elements".But we have done it,our project have a file names"values-zh" in the file have a xml file names "string-zh"  it have chinese interface elements.
As a team leader  I have the responsibility to ensure my team member's score which is got by their strive.So please check our Phase 2 again.Thank you very much,and have a good night~

## Above all,thank you for teaching us 4 weeks,i got  knowledge from your class, thank you.

发自Android Coremail邮箱

"Dr. Brian Bansenauer" notifications@github.com写到：

**Comment by Bansenauer-Cascadia** [comment]
RE_ASSESSMENT
**Complete and correct submissions:**

---
- All team members have committed content to the prototype branch
- App prototype uses good android coding practices as discussed in class
- Four (4) screens that clearly demonstrate behavior from at least two use cases
- One (1) data layout element (List or Grid) using a data adapter
- Two (2) Fragments that communicate via the Activity and respond to the Back button
- Localization in English and Chinese for all interface elements
- BONUS: Implementing music player
- BONUS: Implementing database login and change password
- BONUS: Implementing text animation
  _______________
  **Notes:** Excellent work - a nice start to your app. Your prototype shows your design ideas well. I especially like the additional touches with the music and weather in "Write Diary"

**Comment by Bansenauer-Cascadia** [comment]
OK _ I have updated your code review. Thank you for watching out for your team.

Brian
On Apr 3, 2015, at 12:29 AM, 12301154-jinsongkui <notifications@github.com<mailto:notifications@github.com>> wrote:

Dear teacher,my name is jinsongkui-12301154,is your android class student,and i am the Team 29 leader,for Phase 2 ,you say that our team missong"Localization in English and Chinese for all interface elements".But we have done it,our project have a file names"values-zh" in the file have a xml file names "string-zh" it have chinese interface elements.
As a team leader I have the responsibility to ensure my team member's score which is got by their strive.So please check our Phase 2 again.Thank you very much,and have a good night~

## Above all,thank you for teaching us 4 weeks,i got knowledge from your class, thank you.

发自Android Coremail邮箱

"Dr. Brian Bansenauer" <notifications@github.com<mailto:notifications@github.com>>写到：

**Pull request closed without merging**
